1. What is a Python library? Why do we use Python libraries?

Ans: A Python library is a collection of pre-written code, functions, and modules that can be used to perform various tasks without having to write the code from scratch. These libraries provide a set of tools and functionalities that can be easily integrated into python programs, allowing to leverage existing solutions and speed up development.

Python libraries are used for several reasons:

Code Reusability: Libraries contain pre-written code, enabling developers to reuse existing implementations rather than writing everything from scratch. This promotes efficient and modular coding practices.

Productivity: By using libraries, developers can save time and effort. They don't need to reinvent the wheel for common functionalities, allowing them to focus on solving specific problems or implementing unique features.

Community Contributions: Python has a large and active community of developers who contribute to the creation and maintenance of libraries. This collaborative effort results in a wealth of resources that can benefit Python programmers.

Performance Optimization: Many Python libraries are optimized for performance and written in languages like C or Cython, providing faster execution compared to equivalent pure Python code.

Specialized Functionality: Python ibraries offer specialized functionality in various domains, such as data analysis, machine learning, web development, scientific computing, and more. Using these libraries allows developers to leverage domain-specific expertise.

Popular Python libraries include NumPy for numerical computing, Pandas for data manipulation, Matplotlib for data visualization, TensorFlow and PyTorch for machine learning, Django and Flask for web development, and many more.

In summary, Python libraries are powerful tools that simplify coding, enhance productivity, and enable developers to tackle a wide range of tasks efficiently.

2. What is the difference between Numpy array and List?

Ans: In NumPy arrays, all elements must have the same data type, whereas lists can contain elements of different data types.

NumPy arrays are homogeneous, providing more efficient storage and operations for numerical data.

NumPy arrays are more memory-efficient than lists. They are stored in contiguous memory blocks, allowing for better performance in terms of memory access and manipulation.

Lists in Python store references to objects, which results in less memory efficiency, especially when dealing with large datasets.

NumPy arrays provide better performance for mathematical operations, especially when working with large datasets. This is because NumPy is implemented in C and optimized for numerical computations. Lists are more flexible but may not perform numerical operations.

NumPy arrays offer a range of built-in functions and methods for array manipulation, linear algebra, statistical operations, and more. Lists provide general-purpose functionality but lack the specialized features for numerical computations available in NumPy.

NumPy provides a variety of functions and methods specifically designed for numerical operations, making it more convenient for mathematical tasks.
Lists are more versatile and can be used for a broader range of tasks but may require more explicit iterations and operations for numerical computations.

3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [21]:
import numpy as np
data = [[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

arr = np.array(data)
print(f"Array shape: {arr.shape}")
print(f"Array Size: {arr.size}")
print(f"Array Dimension: {arr.ndim}")

Array shape: (3, 4)
Array Size: 12
Array Dimension: 2


4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [27]:
data = [[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

arr = np.array(data)
print(f"First row: {arr[0]}")

First row: [1 2 3 4]


5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [32]:
data = [[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

arr = np.array(data)
print(f"Element at the third row and fourth column: {arr[2,3]}")

Element at the third row and fourth column: 12


6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [10]:
data = [[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

arr = np.array(data)
odd_indexed_elements = arr[: , 1::2]
print(f"Odd-indexed elements: {odd_indexed_elements}")

Odd-indexed elements: [[ 2  4]
 [ 6  8]
 [10 12]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [19]:
import numpy as np
random_matrix = np.random.rand(3, 3)

print(random_matrix)



[[0.96447408 0.07416542 0.05283716]
 [0.55228742 0.75715394 0.74900039]
 [0.24689978 0.93140543 0.85562682]]


8. Describe the difference between np.random.rand and np.random.randn?

np.random.rand:

This function generates random numbers from a uniform distribution over the half-open interval [0.0, 1.0). In other words, it produces random values between 0 (inclusive) and 1 (exclusive). It takes dimensions as arguments, allowing to create random arrays or matrices of a specified shape.

np.random.randn:

This function generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1). It returns samples with a bell-shaped curve centered around 0. Like np.random.rand, it also takes dimensions as arguments.

9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [39]:
data = [[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

# Method 1
arr = np.array(data)
reshaped_array = np.reshape(data, (2,2,3))
print(reshaped_array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [43]:
# Method 2
arr1 = np.array(data)
expanded_array = np.expand_dims(data, axis = 2)
print(expanded_array)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


10. How to transpose the following array in NumPy?
[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [47]:
import numpy as np

data = [[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]

arr = np.array(data)
arr_transposed = arr.T

print("Transposed Array:")
print(arr_transposed)

Transposed Array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:
Matrix A2: [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2: [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python:
1. Index wise multiplication
2. Matix multiplication
3. Add both the matrics
4. Subtact matrix B from A
5. Divide Matrix B by A

In [76]:
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

# Index wise multiplication
Index_wise_multiplication = A2*B2
print("Index_wise_multiplication")
print(Index_wise_multiplication)

# Matix multiplication
Matix_multiplication = np.dot(A2, B2.T)
print("\nMatix multiplication")
print(Matix_multiplication)

# Add both the matrics
Matrix_addition = A2 + B2
print("\nMatrix addition")
print(Matrix_addition)

# Subtact matrix B from A
Matrix_subtraction = B2 - A2
print("\nMatrix subtraction")
print(Matrix_subtraction)

# Divide Matrix B by A
Matrix_division = B2/A2
print("\nMatrix division")
print(Matrix_division)

Index_wise_multiplication
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Matix multiplication
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Matrix addition
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Matrix subtraction
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Matrix division
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12. Which function in Numpy can be used to swap the byte order of an array?

The byteswap function can be used to swap the byte order of an array. This function swaps the byte order of the elements in the array, and it can be applied to arrays of different data types. The byteswap function is particularly useful when dealing with binary data and to ensure the correct byte order for compatibility with other systems.

In [70]:
# Example

# Create an array with integers
arr = np.array([1, 2, 3, 4], dtype = np.int32)

# Swap the byte order
arr_swapped = arr.byteswap()

print("Original array:", arr)
print("Array after byte swapping:", arr_swapped)


Original array: [1 2 3 4]
Array after byte swapping: [16777216 33554432 50331648 67108864]


13. What is the significance of the np.linalg.inv function?

Ans: np.linalg.inv is a versatile function that plays a key role in solving linear systems, performing numerical computations, and enabling efficient matrix manipulations in various scientific and engineering applications.

14. What does the np.reshape function do, and how is it used?

The np.reshape function is used to change the shape of an array without changing its data. It returns a new array with the specified shape while preserving the original data. The function is commonly employed to manipulate the dimensions of an array to suit the requirements of different operations or to match the input shape expected by certain algorithms.

In [73]:
# Create a 1D array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshape to a 2x3 matrix
reshaped_array = np.reshape(original_array, (2, 3))

print("Original Array:")
print(original_array)

print("\nReshaped Array:")
print(reshaped_array)


Original Array:
[1 2 3 4 5 6]

Reshaped Array:
[[1 2 3]
 [4 5 6]]


15. What is broadcasting in Numpy?

Broadcasting is a powerful mechanism that allows arrays of different shapes and sizes to be combined, manipulated, and operated upon without the need for explicit copying or redundant code. Broadcasting simplifies the process of performing element-wise operations on arrays of different shapes by implicitly extending the smaller array to match the shape of the larger array.